### ISSUE TITLE
Long Array type not supported

### ISSUE THREAD

**Issue by Iykury** [C4K3/nbted#1]
I tried to edit an NBT file with an array of longs (which is a tag type that was added in 1.12 back in 2017), but got this error:
```
Error: Unable to parse test.nbt, are you sure it's an NBT file?
        caused by: Got unknown type id c trying to read NBT compound
For help, run with --help or read the manpage.
```

When I removed the array using NBTExplorer and tried again, it loaded fine, so I know that's what's causing the problem.

**Comment by devvmh** [comment]
+1 I am affected by this too. Seems to happen when I interact with horses for some reason (but I haven't inspected the file with NBTExplorer yet)

@C4K3 I'm no rust expert but if I pulled the code and worked on this are you active enough to review a pull request?
